### ISSUE TITLE
Ability to only create pages?

### ISSUE THREAD

**Issue by R4356th** [Kenny2github/mw-api-client#12]
It would be useful to be able to only "edit" pages if they do not exist already. This can be done by passing the `createonly` parameter.

**Comment by Kenny2github** [comment]
This isn't directly supported currently, but can be accomplished with
```py
wiki.page(title).edit(content, summary, createonly=True)
```
since arbitrary keyword arguments are [passed as API parameters](https://github.com/Kenny2github/mw-api-client/blob/9cec14d412bada48f284dbccc9978e5fb25ccd04/mw_api_client/page.py#L182). Note that `wiki.page(title)` does not require the page to exist (potentially unless `getinfo` logic fails).

**Comment by R4356th** [comment]
Thank you! That satisfies my use case.
